name: "Networking CI"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runsOn }}
    env:
      DEVELOPER_DIR: "/Applications/${{ matrix.xcode }}.app/Contents/Developer"
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'iOS 18.2, Xcode 16.2'
            destination: 'OS=18.2,name=iPhone 16 Pro'
            xcode: 'Xcode_16.2'
            runsOn: macos-15
          - name: 'macOS 15, Xcode 16.2'
            destination: 'platform=macOS'
            xcode: 'Xcode_16.2'
            runsOn: macos-15
    steps:
      - uses: actions/checkout@v4

      - name: 'Running unit tests on ${{ matrix.name }}'
        run: |
            set -o pipefail && \
            xcodebuild clean test -resultBundlePath "TestResults-${{ matrix.name }}" -skipPackagePluginValidation -scheme "Networking" -destination "${{ matrix.destination }}" | tee "build-log-${{ matrix.name }}.txt" | xcpretty

      # Missing Xcode 16 support
      # https://github.com/kishikawakatsumi/xcresulttool/issues/765
      # - uses: kishikawakatsumi/xcresulttool@v1
      #   with:
      #     path: 'TestResults-${{ matrix.name }}.xcresult'
      #     title: '${{ matrix.name }} Test Results'
      #   if: success() || failure()

      - name: 'Upload Build Log'
        uses: actions/upload-artifact@v4
        with:
          name: 'build-log-${{ matrix.name }}'
          path: 'build-log-${{ matrix.name }}.txt'
        if: success() || failure()
