name: "Networking CI"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  macOS:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runsOn }}
    env:
      DEVELOPER_DIR: "/Applications/${{ matrix.xcode }}.app/Contents/Developer"
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'MacOS 13, Xcode 15.1, Swift 5.9.0'
            xcode: 'Xcode_15.1'
            runsOn: 'macos-13'
          - name: 'MacOS 13, Xcode 14.3.1, Swift 5.8.0'
            xcode: 'Xcode_14.3.1'
            runsOn: 'macos-13'
    steps:
    - uses: actions/checkout@v4

    - name: ${{ matrix.name }}
      run: swift test

  iOS:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runsOn }}
    env:
      DEVELOPER_DIR: "/Applications/${{ matrix.xcode }}.app/Contents/Developer"
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'iOS 17.0'
            destination: 'OS=17.0,name=iPhone 15 Pro'
            xcode: 'Xcode_15.1'
            runsOn: macos-13
          - name: 'iOS 16.4'
            destination: 'OS=16.4,name=iPhone 14 Pro'
            xcode: 'Xcode_14.3.1'
            runsOn: macos-13
    steps:
      - uses: actions/checkout@v4

      - name: ${{ matrix.name }}
        run: |
            set -o pipefail && \
            xcodebuild -skipPackagePluginValidation -scheme "Networking" -destination "${{ matrix.destination }}" clean test | xcpretty

